spring:
  application:
    name: e_commerce

  datasource:
    url: jdbc:postgresql://localhost:5400/ecommerce
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

ai:
  openai:
    base-url: https://api.openai.com
    api-key: ${OPENAI_API_KEY}
    model: gpt-4o-mini


logging:
  level:
    com.groom.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
